### ISSUE TITLE
how to get train_utils

### ISSUE THREAD

**Issue by YoHoSo** [TengyuDeng/lyrics-transcription-with-pitch-onset#1]
Hi, author, we are interested in your code and we are wondering where can we get the train_utils code.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/112539360/196690873-3904ebb5-38b0-432e-a3e7-3ae1a52b427f.png">

**Comment by TengyuDeng** [comment]
Thank you for reporting the issue. The missing files have been added to the repository.

**Comment by YoHoSo** [comment]
Thanks for uploading the new code
